<?php
include('./fonction/Function.php');
/*if(isset($_POST['ajouterAgencesubmit'])){
$nomAgence=$_POST['nomAgence'];
$mail=$_POST['mail'];
$description=$_POST['description'];
$adresse=$_POST['adresse'];
$tel=$_POST['tel'];
$fax=$_POST['fax'];
$couverture=$_POST['couverture'];
$Latitude=$_POST['Latitude'];
$Longitude=$_POST['Longitude'];
ajouter_Agence($_SESSION['infos_generale']['id_entreprise'],$nomAgence,$couverture,$mail,$description,$adresse,$tel,$fax,$Latitude,$Longitude);
}*/
?>
